/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as UnsealRouteImport } from './../routes/unseal'
import { Route as LoginRouteImport } from './../routes/login'
import { Route as AuthenticatedRouteImport } from './../routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './../routes/_authenticated/index'
import { Route as AuthenticatedEnableAuthMethodRouteImport } from './../routes/_authenticated/enable-auth-method'
import { Route as AuthenticatedAccessRouteImport } from './../routes/_authenticated/access'
import { Route as AuthenticatedSplatRouteImport } from './../routes/_authenticated/$'
import { Route as AuthenticatedAccessIndexRouteImport } from './../routes/_authenticated/access.index'
import { Route as AuthenticatedSettingsSealRouteImport } from './../routes/_authenticated/settings.seal'
import { Route as AuthenticatedPoliciesAclRouteImport } from './../routes/_authenticated/policies.acl'
import { Route as AuthenticatedAccessNamespacesRouteImport } from './../routes/_authenticated/access.namespaces'

const UnsealRoute = UnsealRouteImport.update({
  id: '/unseal',
  path: '/unseal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEnableAuthMethodRoute =
  AuthenticatedEnableAuthMethodRouteImport.update({
    id: '/enable-auth-method',
    path: '/enable-auth-method',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccessRoute = AuthenticatedAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSplatRoute = AuthenticatedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccessIndexRoute =
  AuthenticatedAccessIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccessRoute,
  } as any)
const AuthenticatedSettingsSealRoute =
  AuthenticatedSettingsSealRouteImport.update({
    id: '/settings/seal',
    path: '/settings/seal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPoliciesAclRoute =
  AuthenticatedPoliciesAclRouteImport.update({
    id: '/policies/acl',
    path: '/policies/acl',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccessNamespacesRoute =
  AuthenticatedAccessNamespacesRouteImport.update({
    id: '/namespaces',
    path: '/namespaces',
    getParentRoute: () => AuthenticatedAccessRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/unseal': typeof UnsealRoute
  '/$': typeof AuthenticatedSplatRoute
  '/access': typeof AuthenticatedAccessRouteWithChildren
  '/enable-auth-method': typeof AuthenticatedEnableAuthMethodRoute
  '/': typeof AuthenticatedIndexRoute
  '/access/namespaces': typeof AuthenticatedAccessNamespacesRoute
  '/policies/acl': typeof AuthenticatedPoliciesAclRoute
  '/settings/seal': typeof AuthenticatedSettingsSealRoute
  '/access/': typeof AuthenticatedAccessIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/unseal': typeof UnsealRoute
  '/$': typeof AuthenticatedSplatRoute
  '/enable-auth-method': typeof AuthenticatedEnableAuthMethodRoute
  '/': typeof AuthenticatedIndexRoute
  '/access/namespaces': typeof AuthenticatedAccessNamespacesRoute
  '/policies/acl': typeof AuthenticatedPoliciesAclRoute
  '/settings/seal': typeof AuthenticatedSettingsSealRoute
  '/access': typeof AuthenticatedAccessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/unseal': typeof UnsealRoute
  '/_authenticated/$': typeof AuthenticatedSplatRoute
  '/_authenticated/access': typeof AuthenticatedAccessRouteWithChildren
  '/_authenticated/enable-auth-method': typeof AuthenticatedEnableAuthMethodRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/access/namespaces': typeof AuthenticatedAccessNamespacesRoute
  '/_authenticated/policies/acl': typeof AuthenticatedPoliciesAclRoute
  '/_authenticated/settings/seal': typeof AuthenticatedSettingsSealRoute
  '/_authenticated/access/': typeof AuthenticatedAccessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/unseal'
    | '/$'
    | '/access'
    | '/enable-auth-method'
    | '/'
    | '/access/namespaces'
    | '/policies/acl'
    | '/settings/seal'
    | '/access/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/unseal'
    | '/$'
    | '/enable-auth-method'
    | '/'
    | '/access/namespaces'
    | '/policies/acl'
    | '/settings/seal'
    | '/access'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/unseal'
    | '/_authenticated/$'
    | '/_authenticated/access'
    | '/_authenticated/enable-auth-method'
    | '/_authenticated/'
    | '/_authenticated/access/namespaces'
    | '/_authenticated/policies/acl'
    | '/_authenticated/settings/seal'
    | '/_authenticated/access/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnsealRoute: typeof UnsealRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unseal': {
      id: '/unseal'
      path: '/unseal'
      fullPath: '/unseal'
      preLoaderRoute: typeof UnsealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/enable-auth-method': {
      id: '/_authenticated/enable-auth-method'
      path: '/enable-auth-method'
      fullPath: '/enable-auth-method'
      preLoaderRoute: typeof AuthenticatedEnableAuthMethodRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/access': {
      id: '/_authenticated/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AuthenticatedAccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$': {
      id: '/_authenticated/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthenticatedSplatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/access/': {
      id: '/_authenticated/access/'
      path: '/'
      fullPath: '/access/'
      preLoaderRoute: typeof AuthenticatedAccessIndexRouteImport
      parentRoute: typeof AuthenticatedAccessRoute
    }
    '/_authenticated/settings/seal': {
      id: '/_authenticated/settings/seal'
      path: '/settings/seal'
      fullPath: '/settings/seal'
      preLoaderRoute: typeof AuthenticatedSettingsSealRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/policies/acl': {
      id: '/_authenticated/policies/acl'
      path: '/policies/acl'
      fullPath: '/policies/acl'
      preLoaderRoute: typeof AuthenticatedPoliciesAclRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/access/namespaces': {
      id: '/_authenticated/access/namespaces'
      path: '/namespaces'
      fullPath: '/access/namespaces'
      preLoaderRoute: typeof AuthenticatedAccessNamespacesRouteImport
      parentRoute: typeof AuthenticatedAccessRoute
    }
  }
}

interface AuthenticatedAccessRouteChildren {
  AuthenticatedAccessNamespacesRoute: typeof AuthenticatedAccessNamespacesRoute
  AuthenticatedAccessIndexRoute: typeof AuthenticatedAccessIndexRoute
}

const AuthenticatedAccessRouteChildren: AuthenticatedAccessRouteChildren = {
  AuthenticatedAccessNamespacesRoute: AuthenticatedAccessNamespacesRoute,
  AuthenticatedAccessIndexRoute: AuthenticatedAccessIndexRoute,
}

const AuthenticatedAccessRouteWithChildren =
  AuthenticatedAccessRoute._addFileChildren(AuthenticatedAccessRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSplatRoute: typeof AuthenticatedSplatRoute
  AuthenticatedAccessRoute: typeof AuthenticatedAccessRouteWithChildren
  AuthenticatedEnableAuthMethodRoute: typeof AuthenticatedEnableAuthMethodRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPoliciesAclRoute: typeof AuthenticatedPoliciesAclRoute
  AuthenticatedSettingsSealRoute: typeof AuthenticatedSettingsSealRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSplatRoute: AuthenticatedSplatRoute,
  AuthenticatedAccessRoute: AuthenticatedAccessRouteWithChildren,
  AuthenticatedEnableAuthMethodRoute: AuthenticatedEnableAuthMethodRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPoliciesAclRoute: AuthenticatedPoliciesAclRoute,
  AuthenticatedSettingsSealRoute: AuthenticatedSettingsSealRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  UnsealRoute: UnsealRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
